import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  final Map<String, Map<String, String>> _localizedValues;

  AppLocalizations(this.locale, this._localizedValues);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  String getText(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'te', 'ta', 'bn', 'mr'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    final Map<String, Map<String, String>> localizedValues = {
      'en': {
        'appTitle': 'SmartAgri Advisor',
        'selectLanguage': 'Select your preferred language',
        'next': 'Next',
        'back': 'Back',
        'skip': 'Skip',
        'getStarted': 'Get Started',
        'changeLanguage': 'Change Language',
        'voiceTutorial': 'Voice Tutorial Available',
        
        // Onboarding screens
        'onboarding1_title': 'Smart Crop Recommendations',
        'onboarding1_desc': 'Get AI-powered suggestions for the best crops based on your soil and climate.',
        'onboarding2_title': 'Real-time Analytics',
        'onboarding2_desc': 'Monitor your farm\'s performance with real-time data and analytics.',
        'onboarding3_title': 'Smart Alerts',
        'onboarding3_desc': 'Get instant notifications about weather changes and crop health.',
        
        // Home screen
        'good_morning': 'Good Morning!',
        'good_afternoon': 'Good Afternoon!',
        'good_evening': 'Good Evening!',
        'hello_farmer': 'Hello Farmer',
        'todays_alerts': 'Today\'s Alerts',
        'soil_status': 'Soil Status',
        'weather_forecast': 'Weather Forecast',
        'live_market_prices': 'Live Market Prices',
        'crop_advice': 'Crop\nAdvice',
        'add_data': 'Add\nData',
        'home': 'Home',
        'scan': 'Scan',
        'chat': 'Chat',
        'advice': 'Advice',
        'profile': 'Profile',
        'crop_health': 'Crop Health',
        'yield_est': 'Yield Est.',
        'expected_this_season': 'Expected this season',
        'humidity': 'Humidity',
        'rice_price_alert': 'Rice prices increased in market',
        'rice_price_desc': 'Rice prices have increased by 8% in the local market.',
        'urgent': 'URGENT',
        'ph_level': 'pH Level: 6.5',
        'optimal_crops': 'Optimal for most crops',
        'current_weather': 'Current Weather',
        'temperature': 'Temperature',
        'five_day_forecast': '5-Day Forecast',
        'today': 'Today',
        'soil_analysis': 'Soil Analysis',
        'ph_level_short': 'pH Level',
        'moisture': 'Moisture',
        'nitrogen': 'Nitrogen',
        'good': 'Good',
        'optimal': 'Optimal',
        'medium': 'Medium',
        'fair': 'Fair',
        'live': 'LIVE',
        'view_detailed_analysis': 'View Detailed Analysis',
      },
      'hi': {
        'appTitle': 'स्मार्टएग्री सलाहकार',
        'selectLanguage': 'अपनी पसंदीदा भाषा चुनें',
        'next': 'अगला',
        'back': 'पीछे',
        'skip': 'छोड़ें',
        'getStarted': 'शुरू करें',
        'changeLanguage': 'भाषा बदलें',
        'voiceTutorial': 'वॉइस ट्यूटोरियल उपलब्ध',
        'onboarding1_title': 'स्मार्ट फसल सिफारिशें',
        'onboarding1_desc': 'अपनी मिट्टी और जलवायु के आधार पर सर्वोत्तम फसलों के लिए एआई-संचालित सुझाव प्राप्त करें।',
        'onboarding2_title': 'रीयल-टाइम विश्लेषण',
        'onboarding2_desc': 'रीयल-टाइम डेटा और विश्लेषण के साथ अपने खेत के प्रदर्शन की निगरानी करें।',
        'onboarding3_title': 'स्मार्ट अलर्ट',
        'onboarding3_desc': 'मौसम परिवर्तन और फसल स्वास्थ्य के बारे में त्वरित सूचनाएं प्राप्त करें।',
        
        // Home screen
        'good_morning': 'सुप्रभात!',
        'good_afternoon': 'नमस्ते!',
        'good_evening': 'शुभ संध्या!',
        'hello_farmer': 'नमस्कार किसान',
        'todays_alerts': 'आज की चेतावनी',
        'soil_status': 'मिट्टी की स्थिति',
        'weather_forecast': 'मौसम पूर्वानुमान',
        'live_market_prices': 'लाइव मार्केट दर',
        'crop_advice': 'फसल\nसलाह',
        'add_data': 'डेटा\nजोड़ें',
        'home': 'होम',
        'scan': 'स्कैन',
        'chat': 'चैट',
        'advice': 'सलाह',
        'profile': 'प्रोफ़ाइल',
        'crop_health': 'फसल स्वास्थ्य',
        'yield_est': 'उत्पादन अनुमान',
        'expected_this_season': 'इस सीजन की अपेक्षा',
        'humidity': 'आर्द्रता',
        'rice_price_alert': 'बाजार में चावल की कीमतें बढ़ीं',
        'rice_price_desc': 'स्थानीय बाजार में चावल की कीमतों में 8% की वृद्धि हुई है।',
        'urgent': 'जरूरी',
        'ph_level': 'पीएच स्तर: 6.5',
        'optimal_crops': 'अधिकांश फसलों के लिए आदर्श',
        'current_weather': 'वर्तमान मौसम',
        'temperature': 'तापमान',
        'five_day_forecast': '5-दिन का पूर्वानुमान',
        'today': 'आज',
        'soil_analysis': 'मिट्टी विश्लेषण',
        'ph_level_short': 'पीएच स्तर',
        'moisture': 'नमी',
        'nitrogen': 'नाइट्रोजन',
        'good': 'अच्छा',
        'optimal': 'आदर्श',
        'medium': 'मध्यम',
        'fair': 'ठीक',
        'live': 'लाइव',
        'view_detailed_analysis': 'विस्तृत विश्लेषण देखें',
      },
      'bn': {
        'appTitle': 'স্মার্টএগ্রি উপদেষ্টা',
        'selectLanguage': 'আপনার পছন্দের ভাষা নির্বাচন করুন',
        'next': 'পরবর্তী',
        'back': 'পিছনে',
        'skip': 'এড়িয়ে যান',
        'getStarted': 'শুরু করুন',
        'changeLanguage': 'ভাষা পরিবর্তন করুন',
        'voiceTutorial': 'ভয়েস টিউটোরিয়াল উপলব্ধ',
        'onboarding1_title': 'স্মার্ট ফসলের সুপারিশ',
        'onboarding1_desc': 'আপনার মাটি এবং জলবায়ু ভিত্তি করে সেরা ফসলের জন্য AI-চালিত পরামর্শ পান।',
        'onboarding2_title': 'রিয়েল-টাইম বিশ্লেষণ',
        'onboarding2_desc': 'রিয়েল-টাইম ডেটা এবং বিশ্লেষণ দিয়ে আপনার খামারের কর্মক্ষমতা নিরীক্ষণ করুন।',
        'onboarding3_title': 'স্মার্ট সতর্কতা',
        'onboarding3_desc': 'আবহাওয়া পরিবর্তন এবং ফসলের স্বাস্থ্য সম্পর্কে তাত্ক্ষণিক বিজ্ঞপ্তি পান।',
        
        // Home screen
        'good_morning': 'সুপ্রভাত!',
        'good_afternoon': 'শুভ বিকেল!',
        'good_evening': 'শুভ সন্ধ্যা!',
        'hello_farmer': 'নমস্কার কৃষক',
        'todays_alerts': 'আজকের সতর্কতা',
        'soil_status': 'মাটির অবস্থা',
        'weather_forecast': 'আবহাওয়ার পূর্বাভাস',
        'live_market_prices': 'লাইভ বাজার দর',
        'crop_advice': 'ফসল\nপরামর্শ',
        'add_data': 'ডেটা\nযোগ করুন',
        'home': 'হোম',
        'scan': 'স্ক্যান',
        'chat': 'চ্যাট',
        'advice': 'পরামর্শ',
        'profile': 'প্রোফাইল',
        'crop_health': 'ফসলের স্বাস্থ্য',
        'yield_est': 'ফলন অনুমান',
        'expected_this_season': 'এই মৌসুমে প্রত্যাশিত',
        'humidity': 'আর্দ্রতা',
        'rice_price_alert': 'বাজারে চালের দাম বৃদ্ধি',
        'rice_price_desc': 'স্থানীয় বাজারে চালের দাম ৮% বৃদ্ধি পেয়েছে।',
        'urgent': 'জরুরি',
        'ph_level': 'পিএইচ লেভেল: ৬.৫',
        'optimal_crops': 'বেশিরভাগ ফসলের জন্য আদর্শ',
        'current_weather': 'বর্তমান আবহাওয়া',
        'temperature': 'তাপমাত্রা',
        'five_day_forecast': '৫-দিনের পূর্বাভাস',
        'today': 'আজ',
        'soil_analysis': 'মাটি বিশ্লেষণ',
        'ph_level_short': 'পিএইচ লেভেল',
        'moisture': 'আর্দ্রতা',
        'nitrogen': 'নাইট্রোজেন',
        'good': 'ভাল',
        'optimal': 'আদর্শ',
        'medium': 'মাঝারি',
        'fair': 'ঠিক আছে',
        'live': 'লাইভ',
        'view_detailed_analysis': 'বিস্তারিত বিশ্লেষণ দেখুন',
      },
      'te': {
        'appTitle': 'స్మార్ట్ అగ్రీ సలహాదారు',
        'selectLanguage': 'మీకు నచ్చిన భాషను ఎంచుకోండి',
        'next': 'తర్వాత',
        'back': 'వెనుకకు',
        'skip': 'దాటవేయి',
        'getStarted': 'ప్రారంభించండి',
        'changeLanguage': 'భాష మార్చు',
        'voiceTutorial': 'వాయిస్ ట్యుటోరియల్ అందుబాటులో ఉంది',
        'onboarding1_title': 'స్మార్ట్ పంట సిఫార్సులు',
        'onboarding1_desc': 'మీ నేల మరియు వాతావరణం ఆధారంగా ఉత్తమ పంటల కోసం AI-ఆధారిత సూచనలను పొందండి.',
        'onboarding2_title': 'రియల్-టైమ్ విశ్లేషణ',
        'onboarding2_desc': 'రియల్-టైమ్ డేటా మరియు విశ్లేషణతో మీ వ్యవసాయ భూమి పనితీరును పర్యవేక్షించండి.',
        'onboarding3_title': 'స్మార్ట్ అలెర్ట్లు',
        'onboarding3_desc': 'వాతావరణ మార్పులు మరియు పంట ఆరోగ్యం గురించి తక్షణ నోటిఫికేషన్లను పొందండి.',
        
        // Home screen
        'good_morning': 'శుభోదయం!',
        'good_afternoon': 'శుభమధ్యాహ్నం!',
        'good_evening': 'శుభసాయంత్రం!',
        'hello_farmer': 'నమస్కారం రైతు',
        'todays_alerts': 'నేటి హెచ్చరికలు',
        'soil_status': 'నేల స్థితి',
        'weather_forecast': 'వాతావరణ వార్త',
        'live_market_prices': 'లైవ్ మార్కెట్ ధరలు',
        'crop_advice': 'పంట\nసలహా',
        'add_data': 'డేటా\nచేర్చండి',
        'home': 'హోమ్',
        'scan': 'స్కాన్',
        'chat': 'చాట్',
        'advice': 'సలహా',
        'profile': 'ప్రొఫైల్',
        'crop_health': 'పంట ఆరోగ్యం',
        'yield_est': 'దిగుబడి అంచనా',
        'expected_this_season': 'ఈ సీజన్ లో అంచనా',
        'humidity': 'తేమ',
        'rice_price_alert': 'మార్కెట్లో బియ్యం ధరలు పెరిగాయి',
        'rice_price_desc': 'స్థానిక మార్కెట్లో బియ్యం ధరలు 8% పెరిగాయి.',
        'urgent': 'అత్యవసరం',
        'ph_level': 'pH స్థాయి: 6.5',
        'optimal_crops': 'చాలా పంటలకు అనుకూలం',
        'current_weather': 'ప్రస్తుత వాతావరణం',
        'temperature': 'ఉష్ణోగ్రత',
        'five_day_forecast': '5-రోజుల వార్త',
        'today': 'ఈరోజు',
        'soil_analysis': 'నేల విశ్లేషణ',
        'ph_level_short': 'pH స్థాయి',
        'moisture': 'తేమ',
        'nitrogen': 'నత్రజని',
        'good': 'మంచిది',
        'optimal': 'అనుకూలం',
        'medium': 'మధ్యమం',
        'fair': 'బాగానే',
        'live': 'లైవ్',
        'view_detailed_analysis': 'వివరణాత్మక విశ్లేషణ చూడండి',
      },
      'ta': {
        'appTitle': 'ஸ்மார்ட் அக்ரி ஆலோசகர்',
        'selectLanguage': 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
        'next': 'அடுத்து',
        'back': 'பின்னால்',
        'skip': 'தவிர்க்கவும்',
        'getStarted': 'தொடங்கவும்',
        'changeLanguage': 'மொழியை மாற்றவும்',
        'voiceTutorial': 'குரல் பயிற்சி கிடைக்கிறது',
        'onboarding1_title': 'ஸ்மார்ட் பயிர் பரிந்துரைகள்',
        'onboarding1_desc': 'உங்கள் மண் மற்றும் காலநிலையின் அடிப்படையில் சிறந்த பயிர்களுக்கான AI-இயக்கப்பட்ட பரிந்துரைகளைப் பெறவும்.',
        'onboarding2_title': 'நிகழ் நேர பகுப்பாய்வு',
        'onboarding2_desc': 'நிகழ்நேர தரவு மற்றும் பகுப்பாய்வுகளுடன் உங்கள் பண்ணையின் செயல்திறனை கண்காணிக்கவும்.',
        'onboarding3_title': 'ஸ்மார்ட் அலாரங்கள்',
        'onboarding3_desc': 'வானிலை மாற்றங்கள் மற்றும் பயிர் ஆரோக்கியம் குறித்த உடனடி அறிவிப்புகளைப் பெறவும்.',
        
        // Home screen
        'good_morning': 'காலை வணக்கம்!',
        'good_afternoon': 'மதிய வணக்கம்!',
        'good_evening': 'மாலை வணக்கம்!',
        'hello_farmer': 'வணக்கம் விவசாயி',
        'todays_alerts': 'இன்றைய எச்சரிக்கைகள்',
        'soil_status': 'மண் நிலை',
        'weather_forecast': 'வானிலை முன்னறிவிப்பு',
        'live_market_prices': 'நேரலை சந்தை விலைகள்',
        'crop_advice': 'பயிர்\nஆலோசனை',
        'add_data': 'தரவு\nசேர்க்கவும்',
        'home': 'முகப்பு',
        'scan': 'ஸ்கேன்',
        'chat': 'அரட்டை',
        'advice': 'ஆலோசனை',
        'profile': 'சுயவிவரம்',
        'crop_health': 'பயிர் ஆரோக்கியம்',
        'yield_est': 'மகசூல் மதிப்பீடு',
        'expected_this_season': 'இந்த பருவத்தில் எதிர்பார்க்கப்படுகிறது',
        'humidity': 'ஈரப்பதம்',
        'rice_price_alert': 'சந்தையில் அரிசி விலை உயர்வு',
        'rice_price_desc': 'உள்ளூர் சந்தையில் அரிசி விலை 8% அதிகரித்துள்ளது.',
        'urgent': 'அவசரம்',
        'ph_level': 'pH அளவு: 6.5',
        'optimal_crops': 'பெரும்பாலான பயிர்களுக்கு சிறந்தது',
        'current_weather': 'தற்போதைய வானிலை',
        'temperature': 'வெப்பநிலை',
        'five_day_forecast': '5-நாள் முன்னறிவிப்பு',
        'today': 'இன்று',
        'soil_analysis': 'மண் பகுப்பாய்வு',
        'ph_level_short': 'pH அளவு',
        'moisture': 'ஈரப்பதம்',
        'nitrogen': 'நைட்ரஜன்',
        'good': 'நல்லது',
        'optimal': 'சிறந்தது',
        'medium': 'மத்திய',
        'fair': 'நியாயமான',
        'live': 'நேரலை',
        'view_detailed_analysis': 'விரிவான பகுப்பாய்வைக் காண்க',
      },
      'mr': {
        'appTitle': 'स्मार्टएग्री सल्लागार',
        'selectLanguage': 'तुमची पसंतीची भाषा निवडा',
        'next': 'पुढे',
        'back': 'मागे',
        'skip': 'वगळा',
        'getStarted': 'सुरुवात करा',
        'changeLanguage': 'भाषा बदला',
        'voiceTutorial': 'व्हॉइस ट्यूटोरियल उपलब्ध',
        'onboarding1_title': 'स्मार्ट पीक शिफारसी',
        'onboarding1_desc': 'तुमच्या माती आणि हवामानावर आधारित सर्वोत्तम पिकांसाठी AI-चालित सूचना मिळवा.',
        'onboarding2_title': 'रिअल-टाइम विश्लेषण',
        'onboarding2_desc': 'रिअल-टाइम डेटा आणि विश्लेषणासह तुमच्या शेताच्या कामगिरीचे निरीक्षण करा.',
        'onboarding3_title': 'स्मार्ट अलर्ट',
        'onboarding3_desc': 'हवामान बदल आणि पीक आरोग्याबद्दल त्वरित सूचना मिळवा.',
        
        // Home screen
        'good_morning': 'सुप्रभात!',
        'good_afternoon': 'शुभ दुपार!',
        'good_evening': 'शुभ संध्याकाळ!',
        'hello_farmer': 'नमस्कार शेतकरी',
        'todays_alerts': 'आजचे अलर्ट',
        'soil_status': 'माती स्थिती',
        'weather_forecast': 'हवामान अंदाज',
        'live_market_prices': 'थेट मार्केट दर',
        'crop_advice': 'पीक\nसल्ला',
        'add_data': 'डेटा\nजोडा',
        'home': 'होम',
        'scan': 'स्कॅन',
        'chat': 'चॅट',
        'advice': 'सल्ला',
        'profile': 'प्रोफाइल',
        'crop_health': 'पीक आरोग्य',
        'yield_est': 'उत्पादन अंदाज',
        'expected_this_season': 'या हंगामात अपेक्षित',
        'humidity': 'आर्द्रता',
        'rice_price_alert': 'बाजारात तांदूळ दर वाढले',
        'rice_price_desc': 'स्थानिक बाजारात तांदूळाचे दर 8% वाढले आहेत.',
        'urgent': 'तातडीचे',
        'ph_level': 'pH पातळी: 6.5',
        'optimal_crops': 'बहुतेक पिकांसाठी योग्य',
        'current_weather': 'सध्याचे हवामान',
        'temperature': 'तापमान',
        'five_day_forecast': '5-दिवसांचा अंदाज',
        'today': 'आज',
        'soil_analysis': 'माती विश्लेषण',
        'ph_level_short': 'pH पातळी',
        'moisture': 'आर्द्रता',
        'nitrogen': 'नायट्रोजन',
        'good': 'चांगले',
        'optimal': 'योग्य',
        'medium': 'मध्यम',
        'fair': 'ठीक',
        'live': 'थेट',
        'view_detailed_analysis': 'तपशीलवार विश्लेषण पहा',
      },
    };

    return AppLocalizations(locale, localizedValues);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
